# Generated by Django 6.1 on 2026-08-29 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_teacher_student1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student1',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.teacher'),
        ),
    ]
