# Generated by Django 6.1 on 2026-08-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_course_student2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student2',
            name='course',
            field=models.ManyToManyField(related_name='courses', to='students.course'),
        ),
    ]
